config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
root "tweets#index"
resources :tweets, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :message, presence: true, length: {minimum: 10, maximum: 20}, uniqueness: true
end

app/controllers/tweets_controller.rb
class TweetsController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
  def show

  end

  def index
    @tweets = Tweet.order(created_at: :desc)
  end
  
  def new
    @tweet = Tweet.new
  end


  def create

    @tweet = Tweet.new(params.require(:tweet).permit(:message))

    if @tweet.save
      flash[:notice] = "Tweet posted!"
      redirect_to new_tweet_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Task 6" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Task 6">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>All Tweets</h1>

<%= link_to "Create New Tweet", new_tweet_path %>

<ul>
  <% @tweets.each do |tweet| %>
    <li><%= tweet.message %></li>
  <% end %>
</ul>

app/views/tweets/new.html.erb
<h1>Post Your Tweet Below!</h1>
<%= link_to "View Tweets", tweets_path %>

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>


<% if @tweet.errors.any? %>
  <ul>
    <% @tweet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with scope: :tweet, url: tweets_path, local: true do |f|%>

<p>
  <%= f.label :message, "Enter the tweet below!" %>
  <br />
  <%= f.text_field :message %>
</p>

<p>
   <%= f.submit %>
</p>

<% end %>